-- 1
COMMIT -- zatwierdza wprowadzone zmiany ostatecznie, po użyciu tego nie można skorzystać z rollback
ROLLBACK -- cofa wprowadzone ostatnio zmiany
SAVEPOINT -- checkpointy, tekie jakby miejsca zapisu do których można później wrócić
-- 2
--komentarz do 2-go
-- 3
insert into emp(id, last_name, first_name, start_date, salary) VALUES
(100,'Karwoski', 'Artur', TO_DATE('2018-10-11', 'yyyy-mm-dd'), 2500);
-- działa bez problemu, ale wkurzające jest, że trzeba uzupełniać ręcznie ID pracownika
-- do sql oracle 12c problem jest rozwiązany używając przy tworzeniu

 --  nazwa_tabeli NUMBER GENERATED by default on null as IDENTITY,

COMMIT -- wykonuje się poprawnie
-- 4
rollback wykonuje się bez problemu
-- 6
--a
UPDATE
    item
SET
    price = price *1.15;
--b
SAVEPOINT S1;
--c
select price from item;
--d
update item set price = price * 1.1;
--e
savepoint S2;
--f
select price from item ;
--g
update item set price = price*1.6;
--h
select price from item;
--i
rollback to S2;
--j
select price from item;
--k
rollback to S1;
--l
select price from item;
--m
commit;

-- 7
set autocommit on;

-- 8
create table region_kopia as select * from region where 1=0;
-- utworzenie kopii tabeli bez banych w środku dzięki warunkowi '1=0'
-- można odrazu stworzyć kopię danych za pomocą
create table region_kopia as select * from region;
-- gdzie skopiuje wszystkie dany odrazu
insert into region_kopia
    select * from region;
-- tutaj dane zostały wprowadzone oddzielnie

-- 9
insert into dept(id, name, region_id)
    select id + 100, SUBSTR(name, 0, 4), region_id from dept;
	-- najlepiej żeby nie było konfliktów to zwiększyć id dość wysoko aburdalną ilość, by nie było problemów w porzyszłości
-- 10
insert into region_kopia(id, name)
    select customer.id, customer.name from customer, ord where customer.id = ord.customer_id and ord.total < 1000;
	
-- 11
update emp set salary = salary * 3 where id = 1;

-- 12


-- 13
update emp set salary = salary * 3 where title like 'VP%';

-- 14
delete from emp
    where id >= 100;

-- 15
DROP TABLE region_kopia;